language: groovy
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - chmod +x ./gradlew
  - ./gradlew --no-daemon startDb

install:
  - ./gradlew --no-daemon createTestDb

script:
  - ./gradlew --no-daemon assemble

script:
  - ./gradlew --no-daemon check
