language: groovy
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- "chmod +x ./gradlew"
- "./gradlew --no-daemon startDb"
install:
- "./gradlew --no-daemon createTestDb"
script:
- "./gradlew --no-daemon check"
deploy:
  provider: script
  script: "./gradlew clean assemble bintrayUpload"
  on:
    tags: true
env:
  global:
  - secure: GEcpUr2qT2eQ0BkPr+SS8Ceqxyw7jBlF31xoqtE/kev2NE/XkdwzW7bl5FBbYpF6XW6gFLpMtBekeGdvUq8BbQJ3tj4m2YkTV0ZMiZ5gBnRIp3PRpcR2Hev6hawNv1rW/JOeyVCcOMbzdI8DthncprfTUWPj+inYXfPyLMEPj2IsyXEVKFsJiSF3EjIUVcAZrZLQMrXKxvFG8E1BJkA9aasSnTJEKYgi04J1NF9wFMfE9OWX5IEy4qM/i8nEaC21B+JfFLIqxK/AfBGpNjXVBbeW4qG+3V2jyDGa4oaMA5Ta1+rxwn3fVyg0RsmbtPr6JzxegG0hmudWkewad4HPxC5IfQMxNe3WNWAZyW0pqz7kx1J9jtfgJ0v57w10loTTYjxah71f5cKLaNlXnj/zncoL+/Po7txHlUNKK7+Z1CJwtw5rGDpUz2NdFd1yVyY/5yNLO6Pzm39sfUdXdlcM+E12+vmYIdRZuV7w/c6le6+xqmucRO7xFHpjEtnZ8WDDQq4D6TQK3EwmRJKZMsU9VFMiAoNSyCTFhRWDEcNC1N4MzAHSSa8bQQuZ6kZd2N9CPN08XGrUkTsetDQpkTiarQ7Pd4cwm0NnT701+p2PM+GLx71jPCjWRKAsgaM3EcP7akjwAVMNqDTmDI2l6yDgyb+ysHPCllZsFLOREIOW1v8=
  - secure: Vp2Tt89wx7ZU3up/rE4DDQzLYLJ0YbvDP+kbEAUYDUwTFDfsKB0XaBTZ85bowpLmTLAy+WT7osGHRKRamX4qPNOnC3Ds8aAUygYqhWvwRjLOP7jmMlWedHX8p7bYeVX1tZw6X39GjjZ340/SCnUbZynSPH1FXzpVWObgQupZaO8NNnhZpWI3xP84HTGWhJcfcYX+M5R8gK60l1wQIBmZhCSrnbwcZEQKNW/1SlXPf377yvgY/YoDEJMgffUlg05y/mg1nescA3mBZbs+VrkgW88Ul1g0BLpACmQpu2WVpavePJkicIHuInDevPQvjvVK7BV3ZAKuf4Vg5pASRDKQ3tFqZP9CRfMDW5ogbDneYMGbXCowKFGfAfacGvefpoC5jfeWFQ+AEztZE9GEvfqHVYPN2Vq5/zqq2yu0miNZh7yT2+06jtZYv+klCJa0uG66mC7yeDNVeh5p9r+cDwBpSOiDqck9oT3Q0ouVZpls5n6CfvK7yTiSO9orzDRvm5bCo+5VQhWOO4diX0inUDtiE/IGfE1DSo543A8cpfZ+Sjtrxr5S37HuwOus4VqY1/fh/NAKsjILjx+grgRr1ygNvc0+GGU47PLgnR2SnZWZFF8wUbXbWlSKtOZJ0gsmewu54fGOYxB8fEJ9i38nLfqPVGOn+Yd8lQ1TTXWALHo4O3k=
