language: groovy
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- chmod +x ./gradlew
- "./gradlew --no-daemon startDb"
install:
- "./gradlew --no-daemon createTestDb"
script:
- "./gradlew --no-daemon check"
deploy:
  provider: script
  script: "./gradlew clean assemble bintrayUpload --debug"
  on:
    tags: true
env:
  global:
  - secure: SJcS47PY5rNxhbTk+CXcbjvpYQySclS5Nnlgxmc0STZNjT6Jy3r3+GqKkOhlc3rzQn69YJWKvFqilrvw2/S6tpTctXlke7aYj6vW9sqjL18W1t9onQS0Y9XNmjtA3enR5NpnwcF3vpEbyPH2E30OKuGbFzx6SwD9k+5eeITbwAyrZv2qPLVTc3ko99MGYNR44xcqnBCR0sAZI42T2DY1vOQn0AtSq27aAgut9+9xhLT8lwfi9fn7JEJMAX3PfLtrYWQMAt2mwWbO2CMjLpdMCAZM673/s16EQ/sRyn9X3h9hWvTVRSnYsKzfJKegCt4OYZuHzfsZ2T60uYXXXhfa+X3RfjqaXj3CPwNXnbTrCu353VKKoBKVaZplmRqMzLzd9wdkgBfjmRfKKfVot8gQWu6GaLHvdPykt+rDQFsn4h8GSYBhnkMu1mq62cQBRGxz+9oCIaongiBpDMedJsAu8pazT57Nf5903o5GkQ+Pku0T2t0vibabhxuWioXAxqKbAsF6AZEgAiZ6Wad7tG+AEEP00+G/JvEPaCL4hM9mi53oYFuhrfDuY6PHY3IsN82RMCdzvPB7QeFKKVqsvwiLTg9kJXqzSJj1QFKVCmayfuEFkKYNZGG5/bZSy+ylL8rOr8aMq98O1yjS/mxhs07yx69iq6y1JVOJUEQ0XbB8y+U=
  - secure: zGAwpZNjqdLk0cEyfoDNJOMZ68pmkKoNwQUEv5HOFUHvqshtr/1B/csfXpetvTYxFbA2UQ/cJk4ITdCWcZYyOzSscMULWvDTHQrlrFwbMf4U7gRYLHPZspf4rWXR7XLYPDz1fxVZkM3pATFjyLfAFKCsqAmWkO+qsfigDRQ0an+G7BFxIo1VPCfiQkbXYwSNgKscV1+dEFy66qW6XeAwvljTidPzfMdyIddYBQPguU5RY06A49BeEpdhCd5yiYVkK1sv/vlMe4zVV135HUnLayNHBxoexrAQDV1JCJ0AwDKvEluXdDRXHRFdBcsntKHDqDpa1jUO44uXs59HQtTqgllydc/Ig8X4SbSJyoBPrMp4bzfm0NZxdS1sbYP05lW7SzrrmEvMZ49Qtb4WV/bh0grQ2KTzP56zTlO9eZUlC2eXW33ppllr2St8NjwNUg9fuuGWobKCNKV1pTwonl++jiJ8HuJeMQeGxYksqPchRME+pknzpViEw4dw5zNN20e3kL6VQj0QQV6EWczi8OpLNy6givpBoaEvNlIxGWlMU5wEIDoFYDvpa4Fd6vfp/c6bdLx8R9SEDZBB+3w7B9zbpbOWbZohfE3+EsgRO6Et0i6Hth0mdyUxaQ/vXh+mKGDxVADYONUtFGuerL64Ulz11lPDKk2ZnfRhWdSObG08L/w=
