language: groovy
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- chmod +x ./gradlew
- "./gradlew --no-daemon startDb"
install:
- "./gradlew --no-daemon createTestDb"
script:
- "./gradlew --no-daemon check"
deploy:
  provider: script
  script: "./gradlew clean assemble bintrayUpload --debug"
  on:
    tags: true
env:
  global:
  - secure: kcq63O/MlrK3q7b/BZUCRqI7eUZW3SB3O8SWoTjs/BOGJ9fzPAnRiUSESNa6gU8M7OAcdSOp6NwJeCRc5mdHEBiGLG35xCo+leHIjd7GCT+3ELYlJNPgiAYAwiGoTCUGPVPGhngSdSNXDBS5S51cm3ShO0t2NTEV8lx1xOEZfaCOkdaHd9++X+F4nLqmn6mnNWpDuSCmE3qbwt5XAg0q1wlDilvwNKFxNVsPZorEYGo7pW41CxWqHXGeQfc+XRMbmkX1o/YwEMbCR5mowoVHGaJOQz+DKg9kjtRwr/ezeT0adoCUMHk4VDpcAgG5kc7B04E0tXTL1C5sB5fTQ0Zf9F7By4mN0yZ6olbBa/FbJqQA0bjZBA9CcDBNj3qGR1n37LaYCpJc/vi1JRtg18O8OiLU0mdT6f93PiZqW2PfyD9iIc/BwaHOScTrq06EBYDGKhW+v2/RhCxSjgm9UgMrCjmVUa6sqrAVfmYBcISKCDbLn5qk7mcGZnx/xX4UWu7jiyqcAmLfCsjz/XPErqeK/akt7Kwa0jvLSWIptyzsSoe0Cz0QW8ZJuocmnQNN9vpUjVdrsWxiRNKzr2P8pjEdpJZ7mkDba7JfYvLW65dwCFwFsqaeu1QIC1b2UR9EoMTvbnC6MXGvEbCpaE8PcxaEQ+fFm7hIHWFYoA8FF4i87EQ=
  - secure: AujTpo9O+Kw3JCqt/yYw6pL8O5ga5nFoR17WmEy6tXIsKdZkBDZ3pdIqr0u2QdwUYiwQawrVW61+zd7+BqFxvF2Zw3uIO+29zPlDuOkZzOriw71KfHNb8SOUAl2EBvAmHsKSR6cWN9VjYI76W6viyr2WlKvZeSL6pqWUBW5sIzLd1CaHs8j5P8jD2dnrw+2QAJserKDGKz8q+pXRw6RnDDxAdslQIxX9O4WG7p5jpyjkjAbhhUbuDkvHjFkuWFev96MdD7rM9n+6NxJCo5HOVKgy6z28+YpEmjXB7H6luycyiDGmsvmnCaszTF+I/6bpjIcm15CMpjjvlfAkN9Eu9+32vPOmMz2U8exDAXVXh+aVQL/MiZ7953yxaYVOAKvWa9x29JyfcdNjEjSx9futRlUPYuOWeY7i4vpXbXLZXdUt+XBq/JNS/o2Yalr+MbDECHGlxZ95f2lsSVCsvYuaqzblwP58S+ELunJiqnfGakMhNZ0EIZiMrW6bK4I5HkykeDLZh4Kl7QOXdr8Z+cf89xcAN2696IPB9e8F4gBlNp2SxqRIm7GdBMT3bhR8YSqsoHMBt/JA4HjjN/x9OE5HYLHOTyJYxINstZUf4D/kw+tTFXoh+H02yZLpug7UlFaLaglGM8ip7ghfZj13D3EBD6ExDiDPpTdR+Kps82zW+Jo=
