alter table DDCIL_LAUNCHER_CMD alter column LAUNCH_SCREEN_POPULATE_ENTITY_SCRIPT rename to LAUNCH_SCREEN_POPULATE_ENTITY_SCRIPT__U01162 ^
alter table DDCIL_LAUNCHER_CMD alter column LAUNCH_SCREEN_OPEN_TYPE rename to LAUNCH_SCREEN_OPEN_TYPE__U05718 ^
alter table DDCIL_LAUNCHER_CMD alter column LAUNCH_SCREEN_ENTITY rename to LAUNCH_SCREEN_ENTITY__U61540 ^
alter table DDCIL_LAUNCHER_CMD alter column LAUNCH_SCREEN rename to LAUNCH_SCREEN__U92289 ^
alter table DDCIL_LAUNCHER_CMD alter column LAUNCH_SCRIPT rename to LAUNCH_SCRIPT__U29835 ^
alter table DDCIL_LAUNCHER_CMD alter column LAUNCH_SCRIPT__U29835 set null ;
alter table DDCIL_LAUNCHER_CMD add column DTYPE varchar(31) ;
