alter table DDCIL_LAUNCHER_CMD add constraint FK_DDCIL_LAUNCHER_CMD_ON_GROUP foreign key (GROUP_ID) references DDCIL_LAUNCHER_COMMAND_GROUP(ID);
create index IDX_DDCIL_LAUNCHER_CMD_ON_GROUP on DDCIL_LAUNCHER_CMD (GROUP_ID);
